#index:
#    path: /
#    controller: App\Controller\DefaultController::index
login:
  path: /login
  controller: App\Controller\AuthController::login

registration:
  path: /registration
  controller: App\Controller\AuthController::registration

posts:
  path: /posts
  controller: App\Controller\PostController::posts