#index:
#    path: /
#    controller: App\Controller\DefaultController::index
login:
  path: /api/login
  controller: App\Controller\AuthController::login

registration:
  path: /api/registration
  controller: App\Controller\AuthController::registration

posts:
  path: /api/posts
  controller: App\Controller\PostController::posts
  methods: GET

postsByUser:
  path: /api/posts/{user}
  controller: App\Controller\PostController::postsByUser
  methods: GET

addPost:
  path: /api/post
  controller: App\Controller\PostController::addPost
  methods: POST

getUser:
  path: /api/user
  controller: App\Controller\UserController::user
  methods: GET